"""add room and booking models

Revision ID: 998535987aec
Revises: eaa3cb089b3e
Create Date: 2026-02-20 10:55:17.091318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '998535987aec'
down_revision: Union[str, None] = 'eaa3cb089b3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.drop_column('bookings', 'reason')
    op.add_column('rooms', sa.Column('code', sa.String(length=50), nullable=False))
    op.add_column('rooms', sa.Column('location', sa.String(length=120), nullable=True))
    op.add_column('rooms', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.create_index(op.f('ix_rooms_code'), 'rooms', ['code'], unique=True)
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.drop_column('rooms', 'building')
    op.drop_column('rooms', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('is_active', sa.BOOLEAN(), nullable=False))
    op.add_column('rooms', sa.Column('building', sa.VARCHAR(length=120), nullable=False))
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_code'), table_name='rooms')
    op.drop_column('rooms', 'created_at')
    op.drop_column('rooms', 'location')
    op.drop_column('rooms', 'code')
    op.add_column('bookings', sa.Column('reason', sa.VARCHAR(length=500), nullable=True))
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_column('bookings', 'created_at')
    # ### end Alembic commands ###
